#!/bin/bash

regex="[^/]*$"
for file in ~/dotfiles/.* # Only match hidden files
do
  if [[ -f $file ]]
  then
    if [[ $file =~ $regex ]]
    then
      filename="${BASH_REMATCH[0]}"
      rm ~/$filename
      ln -s $file ~/$filename
    fi
  fi
done


# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install rbenv
brew install rbenv

# install zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
