#!/bin/bash

regex="[^/]*$"
for file in ~/dotfiles/.* # Only match hidden files
do
  if [[ -f $file ]]
  then
    if [[ $file =~ $regex ]]
    then
      filename="${BASH_REMATCH[0]}"
      rm ~/$filename
      ln -s $file ~/$filename
    fi
  fi
done


# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install container stuff
brew install podman
brew install docker-compose

# install rbenv
brew install rbenv
rbenv init

# install zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# fix overwritten .zshrc
if [[ -f ~/.zshrc.pre-oh-my-zsh ]]
  rm ~/.zshrc
  rm ~/.zshrc.pre-oh-my-zsh
  ln -s ~/dotfiles/.zshrc ~/.zshrc
fi

# install aws-cli
curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
sudo installer -pkg AWSCLIV2.pkg -target /
rm AWSCLIV2.pkg

# install asdf, java asdf plugin, and java 8, and set system java to global default java
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
asdf plugin-add java https://github.com/halcyon/asdf-java.git
asdf install java adoptopenjdk-8.0.312+7
asdf global java adoptopenjdk-8.0.312+7

# install heroku cli
brew tap heroku/brew && brew install heroku
